-- Dataset preview
SELECT *
FROM customer;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender AS Gender, SUM(CAST(purchase_amount AS Float)) AS Revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
Where discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(CAST(purchase_amount AS Float)) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND (AVG(review_rating),2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(CAST(purchase_amount AS Float)),2) AS avg_purchase
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
	   COUNT(customer_id) AS total_customer,
	   ROUND(AVG(CAST(purchase_amount AS Float)),2) AS avg_spend, 
	   SUM(CAST(purchase_amount AS Float)) AS total_revenue 
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
	   item_purchased,
	   CAST(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5,2)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;



-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_types as(
	SELECT customer_id, previous_purchases,
		   CASE 
				WHEN previous_purchases <= 5 THEN 'NEW'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal'
				END AS customer_segment
	FROM customer)

SELECT customer_segment, count(*) AS number_of_customers
FROM customer_types
GROUP BY customer_segment
ORDER BY number_of_Customers DESC;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
	SELECT 
		category,
		item_purchased,
		COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased )


SELECT item_rank, category, item_purchased, total_orders 
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
       COUNT(*) AS repeat_buyers,
       CAST(100.0 * COUNT(*) / SUM(COUNT(*)) OVER() AS DECIMAL(5,2)) AS pct
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(CAST(purchase_amount AS Float)) AS revenue
FROM customer
GROUP BY age_group
ORDER BY 
  CASE age_group
    WHEN 'Young Adult' THEN 1
    WHEN 'Adult'       THEN 2
    WHEN 'Middle-Aged' THEN 3
    WHEN 'Senior'      THEN 4
  END;


-- Q11. What is the average total spending per customer? And who are the top 10 customers in terms of revenue?

-- Part One: Estimated Average Spending per Customer
SELECT 
    ROUND(AVG(CAST(purchase_amount AS FLOAT) * previous_purchases), 2) AS avg_estimated_lifetime_spend
FROM customer;

-- Part Two: Top 10 Customers by Total Discretionary Spending
WITH customer_spending AS (
    SELECT
        customer_id, age_group, purchase_amount AS last_purchase_amount,
        previous_purchases AS total_orders,
        purchase_amount * previous_purchases AS estimated_lifetime_spend,
        CAST(purchase_amount AS FLOAT) * previous_purchases / NULLIF(previous_purchases, 0) AS avg_order_value
    FROM customer
)

SELECT TOP 10
    customer_id, age_group, total_orders, last_purchase_amount,
    avg_order_value, estimated_lifetime_spend,
    CAST(100.0 * estimated_lifetime_spend / SUM(estimated_lifetime_spend) OVER() AS DECIMAL(5,2)) AS revenue_pct_of_total
FROM customer_spending
ORDER BY estimated_lifetime_spend DESC;


-- Q12. What is the best-selling product in each city?
WITH product_sales AS (
    SELECT
        location, item_purchased, COUNT(*) AS customers_count,
        ROW_NUMBER() OVER(PARTITION BY location ORDER BY COUNT(*) DESC) AS rank_num
    FROM customer
    GROUP BY location, item_purchased
)

SELECT location, item_purchased, customers_count
FROM product_sales
WHERE rank_num = 1
ORDER BY location;


-- Q13. Who are the top 10 customers who spend more than the average for their age group in each category?
WITH age_analysis AS (
    SELECT
        customer_id, age_group, purchase_amount,
        ROUND(AVG(CAST(purchase_amount AS Float)) OVER(PARTITION BY age_group),2) AS age_group_avg
    FROM customer
),

ranked_customers AS (
    SELECT
        customer_id, age_group, purchase_amount, age_group_avg,
        ROUND(purchase_amount - age_group_avg,2) AS above_avg,
        ROW_NUMBER() OVER(PARTITION BY age_group ORDER BY purchase_amount - age_group_avg DESC
        ) AS rank_in_group
    FROM age_analysis
    WHERE purchase_amount > age_group_avg
)

SELECT
    customer_id, age_group, purchase_amount,
    age_group_avg, above_avg
FROM ranked_customers
WHERE rank_in_group <= 10
ORDER BY age_group, rank_in_group;


